INSERT INTO categories (slug, name) VALUES
    ('desk',    'Desk'),
    ('kitchen', 'Kitchen'),
    ('outdoor', 'Outdoor');

INSERT INTO origins (code, name, region) VALUES
    ('CN', 'China', 'Asia'),
    ('JP', 'Japan', 'Asia'),
    ('GB', 'United Kingdom', 'Europe'),
    ('LT', 'Lithuania', 'Europe'),
    ('PT', 'Portugal', 'Europe'),
    ('US', 'United States', 'North America');

INSERT INTO products (category_id, origin_id, sku, slug, name, summary, description, price_cents, stock, image) VALUES
    (1, 6, 'DSK-001', 'walnut-monitor-stand', 'Walnut Monitor Stand',
     'Solid walnut riser that lifts your screen to eye level.',
     'Cut from a single piece of American black walnut and finished with hardwax oil. Raises a monitor by 100 mm and leaves room for a keyboard underneath. Felt pads keep it from sliding on a bare desk.',
     8900, 24, 'DS'),
    (1, 3, 'DSK-002', 'brass-desk-lamp', 'Brass Desk Lamp',
     'Warm dimmable light with a weighted base.',
     'An unlacquered brass lamp that patinas over time. Stepless dimmer from 5 to 100 percent, 2700K LED rated for 25,000 hours, and a 2 m braided cord with an inline switch.',
     14500, 8, 'BL'),
    (1, 3, 'DSK-003', 'canvas-cable-roll', 'Canvas Cable Roll',
     'Six pockets for the cables that live in your bag.',
     'Waxed 18 oz canvas with leather ties. Holds a charger, three cables, a dongle and a pair of earbuds without any of it tangling.',
     3200, 61, 'CR'),
    (1, 5, 'DSK-004', 'ceramic-pen-cup', 'Ceramic Pen Cup',
     'Hand-thrown stoneware in a matte oatmeal glaze.',
     'Thrown in small batches, so no two are identical. Food safe, dishwasher safe, and heavy enough that it does not tip when you drop a pen in from height.',
     2400, 0, 'PC'),

    (2, 6, 'KTC-001', 'cast-iron-skillet', 'Cast Iron Skillet 26 cm',
     'Pre-seasoned and ready for the first sear.',
     'Sand-cast in a single pour with a polished cooking surface. Oven safe to 260C, works on induction, and the helper handle makes it manageable when full.',
     6500, 33, 'CI'),
    (2, 2, 'KTC-002', 'pour-over-kettle', 'Pour-Over Kettle',
     'Gooseneck spout for a slow, controlled pour.',
     'Brushed stainless steel with a 1 L capacity and a thermometer set into the lid. The counterweighted handle keeps the balance steady as the kettle empties.',
     7900, 15, 'PK'),
    (2, 4, 'KTC-003', 'linen-tea-towels', 'Linen Tea Towels, Set of 3',
     'Stonewashed flax that gets softer every wash.',
     'European flax, stonewashed so they are absorbent from day one rather than after a month. Generously sized at 50 by 70 cm with a hanging loop.',
     2800, 47, 'TT'),

    (3, 1, 'OUT-001', 'enamel-camp-mug', 'Enamel Camp Mug',
     'Chip-resistant enamel over heavy steel.',
     'Double-dipped enamel with a rolled stainless rim so it does not chip in a pack. Holds 350 ml and is happy sitting directly on coals.',
     1900, 120, 'CM'),
    (3, 3, 'OUT-002', 'waxed-rain-shell', 'Waxed Rain Shell',
     'A light shell that keeps a drizzle out.',
     'Dry-waxed cotton with taped seams and a two-way zip. Packs into its own chest pocket and re-waxes with any standard bar.',
     18900, 6, 'RS'),
    (3, NULL, 'OUT-003', 'folding-trowel', 'Folding Trowel',
     'Stainless blade with depth marks at 10 and 15 cm.',
     'Folds flat to 12 cm and weighs 96 g. The blade locks open with a quarter turn and the handle is knurled so it works with wet hands.',
     2600, 52, 'FT');
